// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leglxznhrozkdacumsym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZ2x4em5ocm96a2RhY3Vtc3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTQ5MjYsImV4cCI6MjA2NTY3MDkyNn0.kb3IooodCEsoKEI19_JEi4ZlPdSFOqZLS-M2rwUtGbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);